module.exports = {
  api: {
    SUCCESS: 'Request Successfull.',
    SERVER_ERROR: 'Error occurred on server. Please, report it back to team.',
    SOMETHING_WENT_WRONG: 'Something went wrong.',
    UNAUTHORIZED_USER: 'Unauthorized User',
    MISSING_QUERY_PARAMETER: 'Please Add Required Query Parameter',
    CREATED: 'Created!',
    UNSUCCESSFULL: 'Request not fullfiled',
    FOUND: 'Resource Successfully fetched !',
    NOT_FOUND: 'Resource Looking for is not found.',
    USER_FOUND: 'User Account Found',
    USER_NOT_FOUND: 'User Account not found!',
    MISSING_CREDENTIALS: 'Required Credentials not given',
    INVALID_CREDENTIALS: 'Credentials not matched',
    EMAIL_NOT_CONFIRMATION: 'Email Not yet confirmed Check your email inbox',
    EMAIL_VERIFICATION_SUCCESSFULL: 'Your Email has verified successfully',
    EMAIL_ALREADY_CONFIRMATION: 'Your Email is already confirmed',
    UPDATE_UNSUCCESSFULL: 'Unable to Update Requested Field',
    UPDATE_SUCCESSFULL: 'All details has been updated!',
    NO_NEW_UPDATE: 'No New Data requested for update',
    PASSWORD_RESET_LINK: 'Password Reset Link Sent to your Email Address',
    PASSWORD_RESET_LINK_NOT_GENERATED:
      'Password Reset Link is not generated by the Current User',
    SAME_AS_PREV_PASSWORD:
      'Password Same as previous Password. You need to input different password',
    LINK_EXPIRED:
      'Given link has expired. Please repeat the process of generation of new Link otherwise contact our team',
  },
  validations: {
    INVALID_UPDATE: "Requested fields can't be updated",
  },
};
